name: Translate Files on PR 🌎

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Clone TAS Repository
        run: |
          git clone https://github.com/Uncover-F/TAS.git
          cd TAS
          # If TAS has any setup requirements, handle them here

      - name: Install Dependencies
        run: |
          pip install requests  # Install other necessary Python packages

      - name: Prepare Translation Config
        run: |
          # Create the configuration file for TAS
          echo '{
            "services": {
              "libretranslate": {
                "url": "https://libretranslate.com"
              }
            },
            "translations": [' > tas-config.json
          
          # List all locale files and append them to the config
          for locale in public/messages/*.json; do
            if [[ "$locale" != "public/messages/en.json" ]]; then
              # Extract locale code from filename (e.g., "fr.json" -> "FR")
              locale_code=$(basename "$locale" .json | tr '[:lower:]' '[:upper:]')
              echo '{
                "source_lang": "en",
                "target_lang": "'${locale_code}'",
                "files": [
                  "public/messages/en.json"
                ],
                "output_directory": "public/messages/"
              },' >> tas-config.json
            fi
          done
          
          # Close the JSON array and object
          echo ']}' >> tas-config.json

      - name: Translate files
        run: |
          # Run TAS translation script
          cd TAS
          # Run the script or command provided by TAS
          python tas_script.py --config ../tas-config.json  # Adjust according to TAS documentation
          
          # Commit and push translated files
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/messages/
          git commit -m "Update locale files with translations from en.json"
          git push origin HEAD:refs/heads/${{ github.head_ref }}
